apiVersion: apps/v1
kind: Deployment
metadata:
  name: farhanday2-deployment
spec:
  selector:
    matchLabels:
      app: farhanday2-pod
  template:
    metadata:
      labels:
        app: farhanday2-pod
    spec:
      containers:
      - name: farhanday2-container
        image: sidlabacr03.azurecr.io/farhanday2:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
