name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sidlabacr03.azurecr.io/farhanday2:latest
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: 'sidlabacr03'
        # Container registry password
        password: 'JFHb3IFYta5QZxR44XzU6j=ch6OhS9GI'
        # Container registry server url
        login-server: 'sidlabacr03.azurecr.io'
    - name: Push the Docker image
      run: docker push sidlabacr03.azurecr.io/farhanday2:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    # - name: Azure Kubernetes set context
    #   uses: Azure/aks-set-context@v1.1
    #   with:
    #     # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
    #     creds: ${{ secrets.AKS_CREDS }} 
    #     # Resource Group Name
    #     resource-group: Intel_RG
    #     # AKS Cluster Name
    #     cluster-name: sidlabaks01
    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{secrets.KUBECONFIG}}  
      id: login

    - name: Apply AKS Deployment
      run: kubectl apply -f deployment.yaml

    - name: Apply AKS service Deployment
      run: kubectl apply -f service.yaml

    - name: Check Repo
      run: ls
